version: '3.8'

services:
  mgtbatipro:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
    volumes:
      - .:/app
    restart: unless-stopped